- name: Create Ghost
  kubernetes.core.k8s:
    state: present
    src: ghost/ghost-deployment.yml

- name: Service Ghost
  kubernetes.core.k8s:
    state: present
    src: ghost/ghost-service.yml




