---
# Deployment for Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: # The variables below could be set on a ConfigMap object
        - name: database__connection__database 
          value: ghost
        - name: database__connection__user
          value: ghostuser
        - name: database__connection__password
          value: "ola"
        - name: database__connection__host
          value: mysql-service 
          url: http://localhost:3306
        ports:
        - containerPort: 2368
