---
# Deployment for Ghost
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-deployment
  namespace: default
  labels:
    app: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: ghost:5.14.1
        env: # The variables below could be set on a ConfigMap object
        - name: database__connection__database 
          value: ghost
        - name: database__connection__user
          value: ghostuser
        - name: database__connection__password
          value: "ola"
        - name: database__connection__host
          value: mysql-service 
        - name : ghost__host
          value: 34.123.223.190
        - name : url
          value: http://34.123.223.190
        - name: mail__transport
          value: "SMTP"
        - name: mail__options__service
          value: "Google"
        - name: mail__options__host
          value: "smtp.mailgun.org"
        - name: mail__options__auth__user
          value: "ghostgrupo25@gmail.com"
        - name: mail__options__auth__pass
          value: "efnsedohwfayjrhy"
        - name: mail__options__secure
          value: "true"
        - name: mail__options__port
          value: "587"
        ports:
        - containerPort: 2368
    